//! Stage 1: exact single-qubit Clifford recognition, plus the continuous
//! near-Clifford distance metric used by Stage 4's near-Clifford guard.
//!
//! Builds the 24-element table by BFS from the identity using H and S as
//! generators, matched via the global-phase-aligned spectral distance
//! already validated in `matrix.rs`.

use std::collections::HashMap;

use crate::cliffordt::matrix::{Unitary, distance, identity};
use crate::cliffordt::qgate_circuit::{Circuit, Gate};

type Key = [(i64, i64); 4];

/// Phase-invariant, rounded key for a 2x2 unitary: fix the global phase by
/// rotating so the first entry of large-enough magnitude is real and
/// positive, then round to remove floating-point noise.
fn canonical_key(m: &Unitary) -> Key {
    let mut phase = crate::cliffordt::matrix::C64::new(1.0, 0.0);
    for i in 0..4 {
        let v = m[(i / 2, i % 2)];
        if v.norm() > 1e-9 {
            phase = v / v.norm();
            break;
        }
    }
    const SCALE: f64 = 1.0e8;
    let mut out = [(0i64, 0i64); 4];
    for i in 0..4 {
        let v = m[(i / 2, i % 2)] / phase;
        out[i] = ((v.re * SCALE).round() as i64, (v.im * SCALE).round() as i64);
    }
    out
}

pub struct CliffordTable {
    // canonical_key -> (shortest generator word, matrix)
    entries: HashMap<Key, (Vec<Gate>, Unitary)>,
}

impl CliffordTable {
    /// BFS over the single-qubit Clifford group, starting from the
    /// identity, generated by every native single-qubit Clifford gate this
    /// pipeline already has (not just H and S) -- so the recorded word for
    /// each of the 24 elements is genuinely the shortest one available,
    /// e.g. `Sdg` costs 1 gate (itself), not the 3-gate `S,S,S` an H/S-only
    /// generating set would otherwise force. Terminates once no new
    /// (phase-invariant) elements appear -- exactly 24 elements.
    pub fn build() -> Self {
        let generators = [Gate::H, Gate::S, Gate::Sdg, Gate::X, Gate::Y, Gate::Z];
        let id = identity(2);
        let mut entries = HashMap::new();
        entries.insert(canonical_key(&id), (Vec::new(), id.clone()));
        let mut frontier = vec![canonical_key(&id)];

        while !frontier.is_empty() {
            let mut next_frontier = Vec::new();
            for key in frontier {
                let (word, m) = entries.get(&key).cloned().unwrap();
                for generator in &generators {
                    let product = generator.matrix() * &m;
                    let new_key = canonical_key(&product);
                    if entries.contains_key(&new_key) {
                        continue;
                    }
                    let mut new_word = word.clone();
                    new_word.push(generator.clone());
                    entries.insert(new_key, (new_word, product));
                    next_frontier.push(new_key);
                }
            }
            frontier = next_frontier;
        }

        CliffordTable { entries }
    }

    /// Only used by this module's own `table_has_exactly_24_elements` test.
    #[cfg(test)]
    fn len(&self) -> usize {
        self.entries.len()
    }

    /// If `m` is (numerically) exactly one of the 24 Cliffords within
    /// `tol`, return its canonical generator word.
    pub fn exact_match(&self, m: &Unitary, tol: f64) -> Option<Vec<Gate>> {
        let key = canonical_key(m);
        let (word, candidate) = self.entries.get(&key)?;
        if distance(m, candidate) <= tol { Some(word.clone()) } else { None }
    }

    /// Global-phase-aligned spectral distance from `m` to the nearest of
    /// the 24 Cliffords -- cheap (24 small matrix ops). Used to flag
    /// "near-Clifford but not exact" targets before handing them to a
    /// numerically sensitive joint synthesizer.
    pub fn nearest_distance(&self, m: &Unitary) -> f64 {
        self.entries.values().map(|(_, cand)| distance(m, cand)).fold(f64::INFINITY, f64::min)
    }
}

/// Build a single-qubit circuit realizing `word` in program order.
pub fn circuit_from_word(word: &[Gate]) -> Circuit {
    let mut c = Circuit::new(1);
    for gate in word {
        c.push(gate.clone(), vec![0]);
    }
    c
}

/// Rewrite `target`'s single-qubit unitary as `Rz(phi) . (Sdg,H) . Rz(theta)
/// . (H,S) . Rz(lam)` -- an exact (not approximate) ZYZ Euler decomposition
/// via `synthesize::zyz_angles`, with the middle `Ry(theta)` realized as an
/// `S*H`-conjugated `Rz(theta)` (`S*H*Z*(S*H)^dagger = Y`, a standard
/// identity, verified numerically below).
///
/// Used when a block's composed unitary doesn't match one of the 24
/// Cliffords exactly *and* contains a `U3` gate: unlike an exact-Clifford
/// match, a `U3` gate's own parameters are otherwise permanently invisible
/// to every later stage (`Circuit::num_params`/`params`/`set_params` only
/// recognize `Rz`), so a genuine rotation loaded as `rx`/`ry`/`u3` would
/// otherwise never become an adjustable parameter at all -- this same
/// stage's own rounding step, Stage 2's `ScanningGateRemovalPass`, and
/// Stage 3's TRbO would all silently treat it as fixed background
/// structure. This is what actually exposes it, matching what bqskit's
/// `ZXZXZDecomposition` achieves by running unconditionally on every block
/// (not just ones that already happen to be phrased in terms of `Rz`).
pub fn decompose_to_rz_canonical(target: &Unitary) -> Circuit {
    let (theta, phi, lam) = crate::cliffordt::synthesize::zyz_angles(target);
    let mut c = Circuit::new(1);
    c.push(Gate::Rz(lam), vec![0]);
    c.push(Gate::Sdg, vec![0]);
    c.push(Gate::H, vec![0]);
    c.push(Gate::Rz(theta), vec![0]);
    c.push(Gate::H, vec![0]);
    c.push(Gate::S, vec![0]);
    c.push(Gate::Rz(phi), vec![0]);
    c
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cliffordt::matrix::{C64, distance};

    #[test]
    fn sh_conjugation_of_z_rotation_is_y_rotation() {
        // S*H*Z*(S*H)^dagger = Y, the identity `decompose_to_rz_canonical`
        // depends on -- verify it directly rather than trust the by-hand
        // derivation.
        let sh = Gate::S.matrix() * Gate::H.matrix();
        let conjugated_z = &sh * Gate::Z.matrix() * sh.adjoint();
        assert!(distance(&Gate::Y.matrix(), &conjugated_z) < 1e-12);
    }

    #[test]
    fn decompose_to_rz_canonical_is_exact_for_a_generic_unitary() {
        let mut original = Circuit::new(1);
        original.push(Gate::H, vec![0]);
        original.push(Gate::Rz(0.4), vec![0]);
        original.push(Gate::U3(1.1, -0.3, 0.9), vec![0]);
        let target = original.get_unitary();

        let decomposed = decompose_to_rz_canonical(&target);
        assert_eq!(
            decomposed.num_params(),
            3,
            "all three Euler angles should be adjustable Rz gates"
        );
        assert!(distance(&target, &decomposed.get_unitary()) < 1e-10);
    }

    #[test]
    fn decompose_to_rz_canonical_is_exact_for_a_pure_rz() {
        // A lone Rz has theta=0 (the `c.norm() < TINY` branch of
        // zyz_angles) -- confirm the decomposition is still exact even
        // when the "Y-axis" component collapses to nothing.
        let mut original = Circuit::new(1);
        original.push(Gate::Rz(0.77), vec![0]);
        let target = original.get_unitary();

        let decomposed = decompose_to_rz_canonical(&target);
        assert!(distance(&target, &decomposed.get_unitary()) < 1e-10);
    }

    #[test]
    fn table_has_exactly_24_elements() {
        let table = CliffordTable::build();
        assert_eq!(table.len(), 24);
    }

    #[test]
    fn identity_is_an_exact_match() {
        let table = CliffordTable::build();
        let word = table.exact_match(&identity(2), 1e-8).expect("identity should match");
        let built = circuit_from_word(&word).get_unitary();
        assert!(distance(&identity(2), &built) < 1e-8);
    }

    #[test]
    fn t_gate_is_not_an_exact_clifford_match() {
        let table = CliffordTable::build();
        let t = Gate::T.matrix();
        assert!(table.exact_match(&t, 1e-8).is_none());
    }

    #[test]
    fn t_gate_nearest_clifford_distance_is_nonzero_but_bounded() {
        let table = CliffordTable::build();
        let t = Gate::T.matrix();
        let d = table.nearest_distance(&t);
        assert!(d > 0.1, "T should not be too close to any Clifford, got {d}");
        assert!(d < 2.0, "distance should be a bounded operator-norm value, got {d}");
    }

    #[test]
    fn composed_two_t_gates_exactly_matches_s() {
        // T*T == S: the composed rotation should be found as an exact
        // Clifford hit.
        let table = CliffordTable::build();
        let mut c = Circuit::new(1);
        c.push(Gate::T, vec![0]);
        c.push(Gate::T, vec![0]);
        let composed = c.get_unitary();
        let word = table.exact_match(&composed, 1e-8).expect("T*T should be exactly Clifford (S)");
        let built = circuit_from_word(&word).get_unitary();
        assert!(distance(&composed, &built) < 1e-8);
    }

    #[test]
    fn arbitrary_non_clifford_rotation_has_no_exact_match() {
        let table = CliffordTable::build();
        let mut c = Circuit::new(1);
        c.push(Gate::Rz(0.123456), vec![0]);
        assert!(table.exact_match(&c.get_unitary(), 1e-8).is_none());
    }

    #[test]
    fn canonical_key_is_phase_invariant() {
        let m = Gate::H.matrix();
        let phased = m.map(|v| v * C64::new(0.0, 1.0));
        assert_eq!(canonical_key(&m), canonical_key(&phased));
    }
}
