//! Stage 2: exact single-qubit Clifford recognition, plus the continuous
//! near-Clifford distance metric used by Stage 6's near-Clifford guard.
//!
//! Mirrors `build_clifford_words`/`canonical_key`/`word_error`/
//! `nearest_clifford_distance` from `data_processing/compile_cliffordt.py`.
//! Builds the 24-element table by BFS from the identity using H and S as
//! generators, exactly as the Python reference does; matched via the
//! global-phase-aligned spectral distance already validated in `matrix.rs`.

use std::collections::HashMap;

use crate::cliffordt::matrix::{distance, identity, Unitary};
use crate::cliffordt::qgate_circuit::{Circuit, Gate};

type Key = [(i64, i64); 4];

/// Phase-invariant, rounded key for a 2x2 unitary: fix the global phase by
/// rotating so the first entry of large-enough magnitude is real and
/// positive, then round to remove floating-point noise.
fn canonical_key(m: &Unitary) -> Key {
    let mut phase = crate::cliffordt::matrix::C64::new(1.0, 0.0);
    for i in 0..4 {
        let v = m[(i / 2, i % 2)];
        if v.norm() > 1e-9 {
            phase = v / v.norm();
            break;
        }
    }
    const SCALE: f64 = 1.0e8;
    let mut out = [(0i64, 0i64); 4];
    for i in 0..4 {
        let v = m[(i / 2, i % 2)] / phase;
        out[i] = ((v.re * SCALE).round() as i64, (v.im * SCALE).round() as i64);
    }
    out
}

pub struct CliffordTable {
    // canonical_key -> (shortest generator word, matrix)
    entries: HashMap<Key, (Vec<Gate>, Unitary)>,
}

impl CliffordTable {
    /// BFS over the group generated by H and S, starting from the identity.
    /// Terminates once no new (phase-invariant) elements appear -- exactly
    /// 24 for the single-qubit Clifford group.
    pub fn build() -> Self {
        let generators = [Gate::H, Gate::S];
        let id = identity(2);
        let mut entries = HashMap::new();
        entries.insert(canonical_key(&id), (Vec::new(), id.clone()));
        let mut frontier = vec![canonical_key(&id)];

        while !frontier.is_empty() {
            let mut next_frontier = Vec::new();
            for key in frontier {
                let (word, m) = entries.get(&key).cloned().unwrap();
                for generator in &generators {
                    let product = generator.matrix() * &m;
                    let new_key = canonical_key(&product);
                    if entries.contains_key(&new_key) {
                        continue;
                    }
                    let mut new_word = word.clone();
                    new_word.push(generator.clone());
                    entries.insert(new_key, (new_word, product));
                    next_frontier.push(new_key);
                }
            }
            frontier = next_frontier;
        }

        CliffordTable { entries }
    }

    /// Only used by this module's own `table_has_exactly_24_elements` test.
    #[cfg(test)]
    fn len(&self) -> usize {
        self.entries.len()
    }

    /// If `m` is (numerically) exactly one of the 24 Cliffords within
    /// `tol`, return its canonical generator word.
    pub fn exact_match(&self, m: &Unitary, tol: f64) -> Option<Vec<Gate>> {
        let key = canonical_key(m);
        let (word, candidate) = self.entries.get(&key)?;
        if distance(m, candidate) <= tol {
            Some(word.clone())
        } else {
            None
        }
    }

    /// Global-phase-aligned spectral distance from `m` to the nearest of
    /// the 24 Cliffords -- cheap (24 small matrix ops). Used to flag
    /// "near-Clifford but not exact" targets before handing them to a
    /// numerically sensitive joint synthesizer.
    pub fn nearest_distance(&self, m: &Unitary) -> f64 {
        self.entries.values().map(|(_, cand)| distance(m, cand)).fold(f64::INFINITY, f64::min)
    }
}

/// Build a single-qubit circuit realizing `word` in program order.
pub fn circuit_from_word(word: &[Gate]) -> Circuit {
    let mut c = Circuit::new(1);
    for gate in word {
        c.push(gate.clone(), vec![0]);
    }
    c
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cliffordt::matrix::C64;

    #[test]
    fn table_has_exactly_24_elements() {
        let table = CliffordTable::build();
        assert_eq!(table.len(), 24);
    }

    #[test]
    fn identity_is_an_exact_match() {
        let table = CliffordTable::build();
        let word = table.exact_match(&identity(2), 1e-8).expect("identity should match");
        let built = circuit_from_word(&word).get_unitary();
        assert!(distance(&identity(2), &built) < 1e-8);
    }

    #[test]
    fn t_gate_is_not_an_exact_clifford_match() {
        let table = CliffordTable::build();
        let t = Gate::T.matrix();
        assert!(table.exact_match(&t, 1e-8).is_none());
    }

    #[test]
    fn t_gate_nearest_clifford_distance_is_nonzero_but_bounded() {
        let table = CliffordTable::build();
        let t = Gate::T.matrix();
        let d = table.nearest_distance(&t);
        assert!(d > 0.1, "T should not be too close to any Clifford, got {d}");
        assert!(d < 2.0, "distance should be a bounded operator-norm value, got {d}");
    }

    #[test]
    fn composed_two_t_gates_exactly_matches_s() {
        // T*T == S (established earlier this session): the composed
        // rotation should be found as an exact Clifford hit.
        let table = CliffordTable::build();
        let mut c = Circuit::new(1);
        c.push(Gate::T, vec![0]);
        c.push(Gate::T, vec![0]);
        let composed = c.get_unitary();
        let word = table.exact_match(&composed, 1e-8).expect("T*T should be exactly Clifford (S)");
        let built = circuit_from_word(&word).get_unitary();
        assert!(distance(&composed, &built) < 1e-8);
    }

    #[test]
    fn arbitrary_non_clifford_rotation_has_no_exact_match() {
        let table = CliffordTable::build();
        let mut c = Circuit::new(1);
        c.push(Gate::Rz(0.123456), vec![0]);
        assert!(table.exact_match(&c.get_unitary(), 1e-8).is_none());
    }

    #[test]
    fn canonical_key_is_phase_invariant() {
        let m = Gate::H.matrix();
        let phased = m.map(|v| v * C64::new(0.0, 1.0));
        assert_eq!(canonical_key(&m), canonical_key(&phased));
    }
}
