#!/usr/bin/env python3
"""
FLASQ Lower Bound Calculator for Clifford+T circuits in OpenQASM 2 format.

Implements Algorithm 1 from:
  Beverland et al., "FLASQ: FLuid Allocation of Surface code Qubits",
  arXiv:2511.08508 (2025).

The FLASQ model estimates the spacetime volume of a quantum circuit on a 2D
surface code architecture by treating ancilla space as a "fluid" resource that
can be freely rearranged between gates.  It produces a lower bound on the
spacetime volume achievable by any concrete scheduler.

Key quantities (all in units of "blocks" = logical_qubit × logical_timestep):
  V   : total fluid ancilla volume  = sum of per-gate ancilla volumes
  D   : measurement depth bound     = longest serial dependency chain
  Q   : maximum simultaneous qubit usage
  A   : fluid ancilla available     = N_tot - Q
  L   : logical timesteps           = max(V/A, t_react * D)
  S   : total spacetime volume      = L*Q + V

Usage
-----
  python flasq_lower_bound.py circuit.qasm [options]

  --treact FLOAT    Reaction time in logical timesteps (default: 1).
                    This is the classical feedback latency: the time between a surface-code
                    measurement and the moment the decoder's decision reaches the hardware,
                    expressed in logical timesteps (1 timestep = d surface-code cycles).
                    The FLASQ paper uses 10 µs; at d=17 and 1 µs/cycle that is ~0.6 timesteps,
                    rounded to 1. It appears in the T-gate cost and sets the reaction-limited
                    runtime floor L >= t_react * D.
  --vcult FLOAT     Cultivation volume in blocks (default: 26.0, ~d=17 regime)
  --model {conservative,optimistic}  Gate cost model (default: conservative)
  --verbose         Print per-gate breakdown

  N_tot is auto-derived from the QASM qubit count for both the PureMagic layout
  (magic routing, ancilla_rows=1) and the compact bus-routing layout; results are
  printed for each.
"""

import argparse
import math
import re
import sys
from collections import defaultdict
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# PureMagic layout: total qubit count from data qubit count
# ---------------------------------------------------------------------------


def puremagic_ntot(n_data_qubits: int, ancilla_rows: int = 1) -> int:
    """
    Compute the total number of logical qubit slots (data + magic ancilla) in
    the PureMagic surface-code layout generated by ``gen_pure_magic_topo`` in
    ``src/topograph.rs``, given the number of data qubits and the ancilla row
    count (default 1, matching the tool's default).

    The layout is a rectangular grid of ``n_cols × n_rows`` nodes.  Each node
    is one logical qubit slot — either a data patch (X or Z half of a logical
    qubit) or a magic ancilla patch.  Note that each *algorithmic* data qubit
    occupies **two** nodes (one X-stabiliser patch and one Z-stabiliser patch),
    but each magic ancilla occupies exactly one node.  The total qubit count
    reported by PureMagic (``n_qubits = n_data_qubits + n_magic_qubits``) is
    therefore equal to the total node count ``n_rows * n_cols``.

    Parameters
    ----------
    n_data_qubits : int
        Number of data (algorithmic) qubits in the circuit.
    ancilla_rows : int
        Number of ancilla rows between data rows (default 1).

    Returns
    -------
    int
        Total logical qubit slots on the device (data + magic ancilla),
        matching the ``n_qubits`` field reported by PureMagic.
    """
    if n_data_qubits <= 0:
        return 0
    row_spacing = ancilla_rows + 1
    col_spacing = ancilla_rows + 1 if ancilla_rows != 0 else 2
    sq_dim = int(math.floor(math.sqrt(n_data_qubits)))
    patch_rows = sq_dim // 2 + sq_dim % 2
    if patch_rows == 0:
        patch_rows = 1
    patch_cols = math.ceil(n_data_qubits / (2 * patch_rows))
    n_rows = patch_rows * (1 + row_spacing) + row_spacing - 1
    if ancilla_rows == 0:
        n_rows += 1
    n_cols = patch_cols * col_spacing + col_spacing - 1
    # Every node in the grid is one logical qubit slot (n_qubits = n_rows * n_cols).
    return n_rows * n_cols


def busrouting_ntot(n_data_qubits: int, ancilla_rows: int = 0) -> int:
    """
    Compute the total number of logical qubit slots in the PureMagic
    bus-routing layout (``gen_compact_bus_routing_topo`` when ``ancilla_rows=0``,
    or ``gen_bus_routing_topo`` when ``ancilla_rows>0``), as implemented in
    ``src/topograph.rs``.

    Parameters
    ----------
    n_data_qubits : int
        Number of data (algorithmic) qubits in the circuit.
    ancilla_rows : int
        Number of ancilla rows between data rows (default 0 = compact layout).

    Returns
    -------
    int
        Total logical qubit slots on the device (data + bus ancilla),
        matching the ``n_qubits`` field reported by PureMagic in bus-routing mode.
    """
    if n_data_qubits <= 0:
        return 0
    sq_dim = int(math.floor(math.sqrt(n_data_qubits)))
    patch_rows = sq_dim // 2 + sq_dim % 2
    if patch_rows == 0:
        patch_rows = 1
    qubits_per_col = 2 * patch_rows
    n_data_cols = math.ceil(n_data_qubits / qubits_per_col)

    if ancilla_rows == 0:
        # gen_compact_bus_routing_topo
        n_cols = 2 * n_data_cols + 1
        n_rows = 3 + 2 * patch_rows
    else:
        # gen_bus_routing_topo
        bus_rows = patch_rows + 1
        n_cols = 2 * n_data_cols + 3
        n_rows = 2 + 2 * patch_rows + bus_rows

    return n_rows * n_cols


# ---------------------------------------------------------------------------
# Gate ancilla volume table (Table I / Table IV of arXiv:2511.08508)
#
# Conservative model:
#   X/Y/Z, MEAS, INIT : 0
#   H                 : 7
#   S / S†            : 5.5
#   T / T†            : Vol(Cultivate) + t_react + 6
#   CNOT / CZ         : 5 * p(q1, q2)
#   SWAP              : 6 * p(q1, q2)
#   Move              : 5 * p(q1, q2)
#
# Optimistic model:
#   H                 : 1.5
#   S / S†            : 1.5
#   T / T†            : Vol(Cultivate) + t_react + 2.5
#   CNOT / CZ         : 2 * p(q1, q2)
#   SWAP              : 3 * p(q1, q2)
#   Move              : 2 * p(q1, q2)
#
# Measurement depth (same for both models):
#   T / T†            : 1
#   everything else   : 0
# ---------------------------------------------------------------------------

ROUTE_COEFF = {"conservative": 5.0, "optimistic": 2.0}
SWAP_COEFF = {"conservative": 6.0, "optimistic": 3.0}
H_COST = {"conservative": 7.0, "optimistic": 1.5}
S_COST = {"conservative": 5.5, "optimistic": 1.5}
# T cost = vol_cultivate + t_react + base
T_BASE = {"conservative": 6.0, "optimistic": 2.5}
# Cultivation volume multiplier (conservative = 1.5x optimistic)
CULT_MULT = {"conservative": 1.5, "optimistic": 1.0}

# Default probability that the wrong magic state (T† instead of T, or vice versa)
# is injected for a given T gate, requiring a corrective S gate.
# DEFAULT_P_WRONG = 0.5
DEFAULT_P_WRONG = 0.0


# ---------------------------------------------------------------------------
# OpenQASM 2 parser (minimal, handles Clifford+T gate sets)
# ---------------------------------------------------------------------------

# Map from QASM gate names to canonical names used in this tool
GATE_ALIASES: Dict[str, str] = {
    # Paulis
    "x": "X",
    "y": "Y",
    "z": "Z",
    # Hadamard
    "h": "H",
    # Phase / S
    "s": "S",
    "sdg": "Sdg",
    # T
    "t": "T",
    "tdg": "Tdg",
    # Two-qubit
    "cx": "CNOT",
    "cnot": "CNOT",
    "cz": "CZ",
    "swap": "SWAP",
    # Measurements / init (treated as free)
    "measure": "MEAS",
    "reset": "RESET",
    # Barriers (ignored)
    "barrier": "BARRIER",
}


def parse_qasm(text: str) -> Tuple[int, List[Tuple[str, List[int]]]]:
    """
    Parse an OpenQASM 2 string.

    Returns
    -------
    n_qubits : int
        Total number of qubits declared.
    gates : list of (gate_name, [qubit_indices])
        Ordered list of gates with resolved qubit indices.
    """
    qubit_map: Dict[str, int] = {}  # register_name[index] -> global index
    n_qubits = 0
    gates: List[Tuple[str, List[int]]] = []

    # Strip comments
    text = re.sub(r"//[^\n]*", "", text)

    for line in text.splitlines():
        line = line.strip().rstrip(";").strip()
        if not line:
            continue

        # OPENQASM version declaration
        if line.startswith("OPENQASM"):
            continue
        # include
        if line.startswith("include"):
            continue

        # qubit register declaration: qreg name[size];
        m = re.match(r"qreg\s+(\w+)\s*\[(\d+)\]", line)
        if m:
            reg_name, size = m.group(1), int(m.group(2))
            for i in range(size):
                qubit_map[f"{reg_name}[{i}]"] = n_qubits + i
            n_qubits += size
            continue

        # creg / classical register — ignore
        if line.startswith("creg"):
            continue

        # gate definition blocks — skip (we handle primitives only)
        if line.startswith("gate "):
            continue

        # measure q[i] -> c[j]  (treat as free)
        m = re.match(r"measure\s+(\w+\[\d+\])\s*->\s*\w+\[\d+\]", line)
        if m:
            q = _resolve_qubit(m.group(1), qubit_map)
            if q is not None:
                gates.append(("MEAS", [q]))
            continue

        # reset q[i]
        m = re.match(r"reset\s+(\w+\[\d+\])", line)
        if m:
            q = _resolve_qubit(m.group(1), qubit_map)
            if q is not None:
                gates.append(("RESET", [q]))
            continue

        # barrier — ignore
        if line.startswith("barrier"):
            continue

        # Generic gate: name[(params)] qubit_args
        # Strip optional parameters in parentheses (e.g. rz(pi/4))
        line_no_params = re.sub(r"\([^)]*\)", "", line)
        parts = line_no_params.split()
        if not parts:
            continue
        gate_name_raw = parts[0].lower()
        qubit_args_raw = "".join(parts[1:])
        qubit_tokens = [t.strip() for t in qubit_args_raw.split(",") if t.strip()]

        canonical = GATE_ALIASES.get(gate_name_raw)
        if canonical is None:
            # Unknown gate — try to infer from qubit count
            # (e.g. custom single-qubit Clifford decompositions)
            # We conservatively treat unknown single-qubit gates as H-cost,
            # and unknown two-qubit gates as CNOT-cost.
            n_q = len(qubit_tokens)
            if n_q == 1:
                canonical = "H"
            elif n_q == 2:
                canonical = "CNOT"
            else:
                # Skip multi-qubit unknown gates (Toffoli etc.)
                canonical = "UNKNOWN"

        if canonical == "BARRIER":
            continue

        qubits = []
        for tok in qubit_tokens:
            q = _resolve_qubit(tok, qubit_map)
            if q is not None:
                qubits.append(q)

        if canonical != "UNKNOWN":
            gates.append((canonical, qubits))

    return n_qubits, gates


def _resolve_qubit(token: str, qubit_map: Dict[str, int]) -> Optional[int]:
    token = token.strip()
    if token in qubit_map:
        return qubit_map[token]
    # Try without brackets for whole-register references (rare in Clifford+T)
    return None


# ---------------------------------------------------------------------------
# Qubit layout: Manhattan distance between qubits
# ---------------------------------------------------------------------------


def make_layout(n_qubits: int):
    return GridLayout(n_qubits)


class GridLayout:
    """Arrange qubits on a square-ish 2D grid and compute Manhattan distances."""

    def __init__(self, n_qubits: int):
        self.n_qubits = n_qubits
        self.cols = math.ceil(math.sqrt(n_qubits))
        self.rows = math.ceil(n_qubits / self.cols)

    def coords(self, q: int) -> Tuple[int, int]:
        return divmod(q, self.cols)

    def manhattan(self, q1: int, q2: int) -> int:
        r1, c1 = self.coords(q1)
        r2, c2 = self.coords(q2)
        return abs(r1 - r2) + abs(c1 - c2)

    def steiner(self, qubits: List[int]) -> float:
        """
        Approximate rectilinear Steiner tree length for k qubits.
        For k=2: exact Manhattan distance.
        For k=3: (p12 + p13 + p23) / 2  (exact for 3 points).
        For k>=4: minimum spanning tree length (at most 1.5x optimal Steiner).
        """
        if len(qubits) <= 1:
            return 0.0
        if len(qubits) == 2:
            return float(self.manhattan(qubits[0], qubits[1]))
        if len(qubits) == 3:
            q1, q2, q3 = qubits
            return (self.manhattan(q1, q2) + self.manhattan(q1, q3) + self.manhattan(q2, q3)) / 2.0
        # MST via Prim's algorithm for k >= 4
        coords = [self.coords(q) for q in qubits]
        in_tree = [False] * len(qubits)
        min_dist = [float("inf")] * len(qubits)
        min_dist[0] = 0.0
        total = 0.0
        for _ in range(len(qubits)):
            # Pick vertex with minimum distance not yet in tree
            u = min((i for i in range(len(qubits)) if not in_tree[i]), key=lambda i: min_dist[i])
            in_tree[u] = True
            total += min_dist[u]
            ru, cu = coords[u]
            for v in range(len(qubits)):
                if not in_tree[v]:
                    rv, cv = coords[v]
                    d = abs(ru - rv) + abs(cu - cv)
                    if d < min_dist[v]:
                        min_dist[v] = d
        return total


class LinearLayout:
    """Arrange qubits on a 1D line."""

    def __init__(self, n_qubits: int):
        self.n_qubits = n_qubits

    def manhattan(self, q1: int, q2: int) -> int:
        return abs(q1 - q2)

    def steiner(self, qubits: List[int]) -> float:
        if len(qubits) <= 1:
            return 0.0
        lo, hi = min(qubits), max(qubits)
        return float(hi - lo)


# ---------------------------------------------------------------------------
# FLASQ per-gate ancilla volume and measurement depth
# ---------------------------------------------------------------------------


def gate_ancilla_volume(
    gate: str,
    qubits: List[int],
    layout,
    model: str,
    vol_cultivate: float,
    t_react: float,
    p_wrong: float = 0.0,
) -> Tuple[float, float]:
    """
    Return (ancilla_volume, measurement_depth) for a single gate.

    Parameters
    ----------
    gate          : canonical gate name
    qubits        : list of qubit indices the gate acts on
    layout        : Layout object for Manhattan distances
    model         : 'conservative' or 'optimistic'
    vol_cultivate : spacetime volume to cultivate one T state (blocks)
    t_react       : reaction time (logical timesteps)
    p_wrong       : probability that the wrong magic state (T† instead of T,
                    or vice versa) is injected, requiring a corrective S gate
                    (default 0.0 = no wrong-state errors)

    Returns
    -------
    (ancilla_volume, measurement_depth)
      measurement_depth is a float when p_wrong > 0 (expected depth contribution).
    """
    rc = ROUTE_COEFF[model]
    sc = SWAP_COEFF[model]

    if gate in ("X", "Y", "Z", "MEAS", "RESET"):
        return 0.0, 0.0

    if gate == "H":
        return H_COST[model], 0.0

    if gate in ("S", "Sdg"):
        return S_COST[model], 0.0

    if gate in ("T", "Tdg"):
        vol_t = CULT_MULT[model] * vol_cultivate + t_react + T_BASE[model]
        # Wrong-state correction: with probability p_wrong an S gate is applied
        # on the data qubit to convert T† → T (or T → T†).  The S gate adds
        # S_COST ancilla volume and, assuming it takes one logical cycle on the
        # critical path, contributes p_wrong to the expected measurement depth.
        vol_t += p_wrong * S_COST[model]
        depth_t = 1.0 + p_wrong  # expected depth: 1 (T) + p_wrong (S correction)
        return vol_t, depth_t

    if gate in ("CNOT", "CZ"):
        if len(qubits) >= 2:
            p = layout.manhattan(qubits[0], qubits[1])
        else:
            p = 0
        return rc * p, 0.0

    if gate == "SWAP":
        if len(qubits) >= 2:
            p = layout.manhattan(qubits[0], qubits[1])
        else:
            p = 0
        return sc * p, 0.0

    # Fallback for unknown gates treated as H (single-qubit) or CNOT (two-qubit)
    if len(qubits) == 1:
        return H_COST[model], 0.0
    if len(qubits) == 2:
        p = layout.manhattan(qubits[0], qubits[1])
        return rc * p, 0.0

    return 0.0, 0.0


# ---------------------------------------------------------------------------
# Measurement depth bound: longest path in the gate dependency DAG
# ---------------------------------------------------------------------------


def measurement_depth_bound(
    gates: List[Tuple[str, List[int]]], n_qubits: int, p_wrong: float = 0.0
) -> float:
    """
    Compute an upper bound on the (expected) measurement depth of the circuit.

    The measurement depth of a gate is 1 if it is a T/T† gate, 0 otherwise.
    When p_wrong > 0, each T/T† gate has an *expected* depth contribution of
    ``1 + p_wrong``: the base T gate (depth 1) plus a corrective S gate that
    is applied with probability p_wrong and adds one logical cycle on the data
    qubit.

    The measurement depth of the circuit is the length of the longest path
    (in terms of measurement depth) through the gate dependency DAG, where
    edges connect gates that share a qubit.

    We compute this efficiently by tracking, for each qubit, the maximum
    accumulated measurement depth of the last gate that touched it.
    """
    t_depth_contrib = 1.0 + p_wrong  # expected depth per T/T† gate

    # depth[q] = max measurement depth accumulated on qubit q so far
    depth = [0.0] * n_qubits
    max_depth = 0.0

    for gate, qubits in gates:
        if not qubits:
            continue
        # The (expected) measurement depth contribution of this gate
        gate_md = t_depth_contrib if gate in ("T", "Tdg") else 0.0
        # The depth at which this gate starts = max depth of all its qubits
        start_depth = max(depth[q] for q in qubits)
        end_depth = start_depth + gate_md
        for q in qubits:
            depth[q] = end_depth
        if end_depth > max_depth:
            max_depth = end_depth

    return max_depth


# ---------------------------------------------------------------------------
# Maximum simultaneous qubit usage heuristic (Q)
# ---------------------------------------------------------------------------


def max_qubit_usage(gates: List[Tuple[str, List[int]]], n_qubits: int) -> int:
    """
    Heuristic for Q: the maximum number of qubits simultaneously in use.

    We use a simple liveness analysis: a qubit is "live" from its first gate
    to its last gate.  Q is the maximum number of live qubits at any point.

    For Clifford+T circuits with no mid-circuit ancilla allocation this is
    simply n_qubits (all qubits are live throughout).  We implement the full
    heuristic for generality.
    """
    first_use = {}
    last_use = {}
    for idx, (gate, qubits) in enumerate(gates):
        for q in qubits:
            if q not in first_use:
                first_use[q] = idx
            last_use[q] = idx

    if not first_use:
        return n_qubits

    # Sweep through gate indices and count live qubits
    events = defaultdict(int)
    for q in first_use:
        events[first_use[q]] += 1
        events[last_use[q] + 1] -= 1

    live = 0
    max_live = 0
    for idx in range(len(gates) + 1):
        live += events[idx]
        if live > max_live:
            max_live = live

    return max_live


# ---------------------------------------------------------------------------
# Main FLASQ algorithm (Algorithm 1)
# ---------------------------------------------------------------------------


def flasq(
    n_qubits: int,
    gates: List[Tuple[str, List[int]]],
    n_tot: Optional[int],
    t_react: float,
    vol_cultivate: float,
    model: str,
    p_wrong: float = 0.0,
    verbose: bool = False,
) -> Dict:
    """
    Apply the FLASQ model to a parsed circuit.

    Parameters
    ----------
    n_qubits      : number of qubits in the circuit
    gates         : list of (gate_name, [qubit_indices])
    n_tot         : total logical qubits on device (None → auto = 2*Q)
    t_react       : reaction time in logical timesteps
    vol_cultivate : spacetime volume to cultivate one T state (blocks)
    model         : 'conservative' or 'optimistic'
    p_wrong       : probability that the wrong magic state is injected per T gate,
                    requiring a corrective S gate (default 0.0)
    verbose       : print per-gate breakdown

    Returns
    -------
    dict with keys: V, D, Q, A, L, S, M, n_tot
    """
    layout = make_layout(n_qubits)

    # --- Per-gate sums ---
    V = 0.0  # total ancilla volume
    M = 0  # T-count (magic states consumed)

    if verbose:
        print(f"\n{'Gate':<12} {'Qubits':<20} {'AncVol':>10} {'MeasD':>6}")
        print("-" * 52)

    for gate, qubits in gates:
        av, md = gate_ancilla_volume(gate, qubits, layout, model, vol_cultivate, t_react, p_wrong)
        V += av
        if gate in ("T", "Tdg"):
            M += 1
        if verbose and av > 0:
            print(f"{gate:<12} {str(qubits):<20} {av:>10.2f} {md:>6}")

    # --- Measurement depth bound ---
    D = measurement_depth_bound(gates, n_qubits, p_wrong)

    # --- Maximum simultaneous qubit usage ---
    Q = max_qubit_usage(gates, n_qubits)

    # --- Fluid ancilla available ---
    if n_tot is None:
        # Default: assume device has 2× the circuit qubits (a modest overhead)
        n_tot = 2 * Q
    A = max(n_tot - Q, 1)  # at least 1 to avoid division by zero

    # --- Logical timesteps (Algorithm 1, line: L = max(V/A, t_react * D)) ---
    L_space = V / A
    L_react = t_react * D
    L = max(L_space, L_react)

    # --- Total spacetime volume ---
    S = L * Q + V

    return {
        "V": V,
        "D": D,
        "Q": Q,
        "A": A,
        "L": L,
        "L_space": L_space,
        "L_react": L_react,
        "S": S,
        "M": M,
        "n_tot": n_tot,
        "vol_cultivate": vol_cultivate,
        "vol_cultivate_eff": CULT_MULT[model] * vol_cultivate,
        "t_react": t_react,
        "p_wrong": p_wrong,
        "model": model,
        "n_gates": len(gates),
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Compute the FLASQ spacetime-volume lower bound for a Clifford+T circuit."
    )
    parser.add_argument("qasm_file", help="Path to OpenQASM 2 circuit file")
    parser.add_argument(
        "--treact",
        type=float,
        default=1.0,
        help=(
            "Reaction time in logical timesteps (default: 1). "
            "This is the classical feedback latency — the time between a surface-code measurement "
            "and the moment the decoder's decision reaches the hardware — expressed in logical "
            "timesteps (1 timestep = d surface-code cycles). "
            "The FLASQ paper uses 10 µs; at d=17 and 1 µs/cycle that is ~0.6 timesteps, rounded to 1. "
            "Appears in the T-gate cost (Vol(T) = Vol(Cultivate) + t_react + base) and sets the "
            "reaction-limited runtime floor L >= t_react * D."
        ),
    )
    parser.add_argument(
        "--vcult",
        type=float,
        default=26.0,
        help=(
            "Spacetime volume to cultivate one T state, in blocks "
            "(logical_qubit × logical_timestep). "
            "Default 26 corresponds roughly to d=17 surface code at ~1e-3 physical error rate. "
            "Set to 0 to ignore cultivation overhead."
        ),
    )
    parser.add_argument(
        "--pwrong",
        type=float,
        default=DEFAULT_P_WRONG,
        help=(
            "Probability that the wrong magic state (T† instead of T, or vice versa) "
            "is injected for a given T gate, requiring a corrective S gate on the data qubit "
            f"(default: {DEFAULT_P_WRONG}). "
            "The S gate adds p_wrong * S_COST ancilla volume per T gate and increases the "
            "expected measurement depth of each T gate from 1 to 1 + p_wrong."
        ),
    )
    parser.add_argument(
        "--layout",
        dest="layout",
        choices=["puremagic", "bus"],
        default="puremagic",
        help=(
            "Which device layout to evaluate (default: puremagic). "
            "'puremagic' uses the magic-routing layout (gen_pure_magic_topo, ancilla_rows=1); "
            "'bus' uses the bus-routing layout (gen_bus_routing_topo, ancilla_rows=1)."
        ),
    )
    parser.add_argument(
        "--verbose", action="store_true", help="Print per-gate ancilla volume breakdown"
    )
    args = parser.parse_args()

    with open(args.qasm_file) as f:
        text = f.read()

    n_qubits, gates = parse_qasm(text)

    # Select layout.
    if args.layout == "puremagic":
        n_tot = puremagic_ntot(n_qubits, ancilla_rows=1)
        n_tot_source = f"PureMagic layout ({n_qubits} data qubits, ancilla_rows=1)"
    else:
        n_tot = busrouting_ntot(n_qubits, ancilla_rows=1)
        n_tot_source = f"Bus-routing layout ({n_qubits} data qubits, ancilla_rows=1)"

    # Run both models.
    rc = flasq(
        n_qubits=n_qubits,
        gates=gates,
        n_tot=n_tot,
        t_react=args.treact,
        vol_cultivate=args.vcult,
        model="conservative",
        p_wrong=args.pwrong,
        verbose=args.verbose,
    )
    ro = flasq(
        n_qubits=n_qubits,
        gates=gates,
        n_tot=n_tot,
        t_react=args.treact,
        vol_cultivate=args.vcult,
        model="optimistic",
        p_wrong=args.pwrong,
        verbose=False,
    )

    W = 14  # column width for model-dependent values
    print(f"{'='*72}")
    print(f"FLASQ Lower Bound for {args.qasm_file}")
    print(f"  Layout: {n_tot_source}")
    print(f"{'='*72}")
    # Model-independent rows
    print(f"  {'Circuit qubits (n_qubits)':<42}: {n_qubits}")
    print(f"  {'Gates parsed':<42}: {rc['n_gates']}")
    print(f"  {'T-count (M)':<42}: {rc['M']}")
    print(f"  {'Wrong-state injection prob (p_wrong)':<42}: {rc['p_wrong']:.2f}")
    print(f"  {'Max simultaneous qubit usage (Q)':<42}: {rc['Q']}")
    print(f"  {'Total device qubits (N_tot)':<42}: {rc['n_tot']}")
    print(f"  {'Fluid ancilla available (A)':<42}: {rc['A']}")
    print(f"  {'Reaction time (t_react, timesteps)':<42}: {rc['t_react']:.1f}")
    print(f"  {'':42s} {'conserv':>{W}}  {'optimist':>{W}}")
    print(f"  {'-'*42} {'-'*W}  {'-'*W}")
    print(
        f"  {'Cultivation volume per T (v_cult, blocks)':<42}: {rc['vol_cultivate_eff']:>{W}.1f}  {ro['vol_cultivate_eff']:>{W}.1f}"
    )
    # Model-dependent rows
    print(f"  {'Total ancilla volume (V, blocks)':<42}: {rc['V']:>{W}.1f}  {ro['V']:>{W}.1f}")
    print(f"  {'Measurement depth bound (D, timesteps)':<42}: {rc['D']:>{W}}  {ro['D']:>{W}}")
    print(
        f"  {'Spacetime-limited timesteps (V/A)':<42}: {rc['L_space']:>{W}.1f}  {ro['L_space']:>{W}.1f}"
    )
    print(
        f"  {'Reaction-limited timesteps (t*D)':<42}: {rc['L_react']:>{W}.1f}  {ro['L_react']:>{W}.1f}"
    )
    print(f"  {'Logical timesteps (L = max above)':<42}: {rc['L']:>{W}.1f}  {ro['L']:>{W}.1f}")
    print(f"  {'FLASQ spacetime volume (S, blocks)':<42}: {rc['S']:>{W}.1f}  {ro['S']:>{W}.1f}")
    print(f"{'='*72}")

    return rc, ro


if __name__ == "__main__":
    main()
